Rename no_umi_dedup to non_umi_dedup. Add implementation non_umi_dedup.

diff --git a/analysis_tools b/analysis_tools
--- a/analysis_tools
+++ b/analysis_tools
@@ -22,17 +22,20 @@ SAMBAMBA_MARKDUP_OVERFLOW_LIST_SIZE=45000000
 REAL_EXECUTE_TRUE="REAL_EXECUTE_TRUE"
 REAL_EXECUTE_FALSE="REAL_EXECUTE_FALSE"
 
-print_flagstat_usage() {
-  echo "Run sambamba flagstat at GCP. "
-  echo "USAGE: $0 run flagstat \ "
+
+print_non_umi_dedup_usage() {
+  echo "Run sambamba markdup at GCP. "
+  echo "USAGE: $0 run non_umi_dedup \ "
   echo "    --input <input-path> \ "
   echo "    --output <output-path> \ "
-  echo "  [-i/--input]                              (Required)    Path to the bam file on which sambamba flagstat will be run,"
+  echo "  [-i/--input]                              (Required)    Path to the bam file on which deduplication will be run,"
   echo "                                                          e.g. gs://some-kind/of/path.bam"
   echo "                                                          Make sure that an index file is also available,"
   echo "                                                          e.g. gs://some-kind/of/path.bam.bai"
-  echo "  [-o/--output]                             (Required)    Path in bucket to which flagstat file will be written,"
-  echo "                                                          e.g. gs://some-other-kind/of/path.flagstat"
+  echo "  [-o/--output]                             (Required)    Path in bucket to which the deduplicated bam will be written,"
+  echo "                                                          e.g. gs://some-other-kind/of/path.bam"
+  echo "                                                          Will also output an index file,"
+  echo "                                                          e.g. gs://some-other-kind/of/path.bam.bai"
   exit 1
 }
 
@@ -49,6 +52,20 @@ print_umi_dedup_usage() {
   echo "                                                          e.g. gs://some-other-kind/of/path.bam"
   echo "                                                          Will also output an index file,"
   echo "                                                          e.g. gs://some-other-kind/of/path.bam.bai"
+  exit 1
+}
+
+print_flagstat_usage() {
+  echo "Run sambamba flagstat at GCP. "
+  echo "USAGE: $0 run flagstat \ "
+  echo "    --input <input-path> \ "
+  echo "    --output <output-path> \ "
+  echo "  [-i/--input]                              (Required)    Path to the bam file on which sambamba flagstat will be run,"
+  echo "                                                          e.g. gs://some-kind/of/path.bam"
+  echo "                                                          Make sure that an index file is also available,"
+  echo "                                                          e.g. gs://some-kind/of/path.bam.bai"
+  echo "  [-o/--output]                             (Required)    Path in bucket to which flagstat file will be written,"
+  echo "                                                          e.g. gs://some-other-kind/of/path.flagstat"
   exit 1
 }
 
@@ -99,8 +116,8 @@ execute_jobs(){
     case ${job_arg} in
       align)
         remaining_args_string="$(align "${remaining_args_string}" "${real_execute}")" || die "Could not complete ${job_arg} job";;
-      no_umi_dedup)
-        remaining_args_string="$(no_umi_dedup "${remaining_args_string}" "${real_execute}")" || die "Could not complete ${job_arg} job";;
+      non_umi_dedup)
+        remaining_args_string="$(non_umi_dedup "${remaining_args_string}" "${real_execute}")" || die "Could not complete ${job_arg} job";;
       umi_dedup)
         remaining_args_string="$(umi_dedup "${remaining_args_string}" "${real_execute}")" || die "Could not complete ${job_arg} job";;
       flagstat)
@@ -128,12 +145,88 @@ align() {
   echo "${remaining_args_string}"
 }
 
-no_umi_dedup() {
+non_umi_dedup() {
   info "Start ${FUNCNAME[0]} job"
 
   local remaining_args_string=$1 && shift
   local real_execute=$1 && shift  # so not a dry run to check the parameter parsing
   [[ -n ${real_execute} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
+
+  local key
+  local input
+  local output
+  while [[ ${#remaining_args_string} -gt 0 ]]
+  do
+    key=$(get_first_word "${remaining_args_string}") || die "Could not get job arg"
+    case $key in
+      -i|--input)  # required
+        remaining_args_string=$(delete_first_word "${remaining_args_string}") || die "Could not remove key arg"
+        input=$(get_first_word "${remaining_args_string}") || die "Could not get ${key} arg"
+        remaining_args_string=$(delete_first_word "${remaining_args_string}") || die "Could not remove ${key} arg";;
+      -o|--output)  # required
+        remaining_args_string=$(delete_first_word "${remaining_args_string}") || die "Could not remove key arg"
+        output=$(get_first_word "${remaining_args_string}") || die "Could not get ${key} arg"
+        remaining_args_string=$(delete_first_word "${remaining_args_string}") || die "Could not remove ${key} arg";;
+      -*)
+        print_error_msg "Unrecognized option: ${key}"
+        print_non_umi_dedup_usage && exit 1;;
+      *)
+        break;;
+    esac
+  done
+
+  # sanity checks
+  local input_error=false
+  if [[ -z ${input} ]]; then
+    print_error_msg "Variable 'input' has not been set"
+    input_error=true
+  fi
+  if [[ -z ${output} ]]; then
+    print_error_msg "Variable 'output' has not been set"
+    input_error=true
+  fi
+  if [[ -n ${input} && ! "${input}" =~ ^gs://[*-/._a-zA-Z0-9]+.bam$ ]]; then
+    print_error_msg "Variable 'input' needs to be set to a path to a bam file in a bucket, e.g. gs://some-kind/of/path.bam"
+    input_error=true
+  fi
+  if [[ -n ${output} && ! "${output}" =~ ^gs://[-/._a-zA-Z0-9]+.bam ]]; then
+    print_error_msg "Variable 'output' needs to be set to a path of the form 'gs://some-kind/of/path.bam'"
+    input_error=true
+  fi
+  if [[ ${input_error} == true ]]; then
+    echo ""
+    print_non_umi_dedup_usage && exit 1
+  fi
+
+  info "Passed ${FUNCNAME[0]} sanity checks"
+  info "Do non-umi dedup:\ninput=${input}\noutput=${output}"
+
+  if [[ "${real_execute}" != "${REAL_EXECUTE_TRUE}" ]]; then
+    info "Skip because of dry-run"
+  elif [[ $(file_exists_in_bucket "${output}") ]]; then
+    info "Skip because output file already exists in bucket"
+  else
+    local thread_count
+    local local_input_path
+    local local_output_path
+    thread_count=$(get_thread_count) || die "Could not get thread count"
+    local_input_path=$(fill_local_cache "${input}") || die "Could not get local version of ${input}"
+    fill_local_cache "${input}.bai" || die "Could not get local version of ${input}.bai"
+    local_output_path=$(get_local_cache_path "${output}") || die "Could not get local version of ${output}"
+
+    info "Start sambamba markdup"
+    "${SAMBAMBA}" markdup -t "${thread_count}" --overflow-list-size="${SAMBAMBA_MARKDUP_OVERFLOW_LIST_SIZE}" \
+        "${local_input_path}" "${local_output_path}" \
+        || die "Could not run sambamba markdup"
+    info "Finished sambamba markdup"
+
+    info "Start sambamba index"
+    "${SAMBAMBA}" index -t "${thread_count}" "${local_output_path}" || die "Could not index bam ${local_output_path}"
+    info "Finished sambamba index"
+
+    upload_from_local_cache "${output}" || die "Failed to upload output to ${output}"
+    upload_from_local_cache "${output}.bai" || die "Failed to upload output.bai to ${output}.bai"
+  fi
 
   info "Finished ${FUNCNAME[0]} job"
 
@@ -215,6 +308,7 @@ umi_dedup() {
         || die "Could not run UMI-Collapse"
     popd || die "Could not cd out of UMI-Collapse dir"
     info "Finished UMI-Collapse"
+
     info "Start sambamba index"
     "${SAMBAMBA}" index -t "${thread_count}" "${local_output_path}" || die "Could not index bam ${local_output_path}"
     info "Finished sambamba index"
