Write code for flagstat (WIP)

diff --git a/analysis_tools b/analysis_tools
--- a/analysis_tools
+++ b/analysis_tools
@@ -22,6 +22,20 @@ SAMBAMBA_MARKDUP_OVERFLOW_LIST_SIZE=45000000
 REAL_EXECUTE_TRUE="REAL_EXECUTE_TRUE"
 REAL_EXECUTE_FALSE="REAL_EXECUTE_FALSE"
 
+print_flagstat_usage(){
+  echo "Run sambamba flagstat at GCP. "
+  echo "USAGE: $0 run \ "
+  echo "    --input <input-path> \ "
+  echo "    --output <output-path> \ "
+  echo "  [-i/--input]                              (Required)    Path to the bam file on which sambamba flagstat will be run,"
+  echo "                                                          e.g. gs://some-kind/of/path.bam"
+  echo "                                                          Make sure that an index file is also available,"
+  echo "                                                          e.g. gs://some-kind/of/path.bam.bai"
+  echo "  [-o/--output]                             (Required)    Path in bucket to which flagstat file will be written,"
+  echo "                                                          e.g. gs://some-kind/of/path.flagstat"
+  exit 1
+}
+
 do_analysis() {
   info "Starting with ${SCRIPT_NAME}"
 
@@ -54,7 +68,11 @@ execute_jobs(){
   # sanity checks
   [[ "${real_execute}" == "${REAL_EXECUTE_TRUE}" ]] || [[ "${real_execute}" == "${REAL_EXECUTE_FALSE}" ]] || \
         die "Did not recognize 'real_execute' argument. Should be ${REAL_EXECUTE_TRUE} or ${REAL_EXECUTE_FALSE}. Was: ${real_execute}"
+  [[ ${#remaining_args_string} -gt 0 ]] || die "No jobs provided"
   info "Passed sanity checks"
+
+  info "Arguments to parse: ${remaining_args_string}"
+  info "Real execute status: ${real_execute}"
 
   local job_arg
   while [[ ${#remaining_args_string} -gt 0 ]]
@@ -83,31 +101,174 @@ execute_jobs(){
 align() {
   info "Start ${FUNCNAME[0]} job"
 
+  local remaining_args_string=$1 && shift
+  local real_execute=$1 && shift  # so not a dry run to check the parameter parsing
+  [[ -n ${real_execute} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
+
+
+
   info "Finished ${FUNCNAME[0]} job"
+
+  echo "${remaining_args_string}"
 }
 
 no_umi_dedup() {
   info "Start ${FUNCNAME[0]} job"
 
+  local remaining_args_string=$1 && shift
+  local real_execute=$1 && shift  # so not a dry run to check the parameter parsing
+  [[ -n ${real_execute} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
+
   info "Finished ${FUNCNAME[0]} job"
+
+  echo "${remaining_args_string}"
 }
 
 umi_dedup() {
   info "Start ${FUNCNAME[0]} job"
 
+  local remaining_args_string=$1 && shift
+  local real_execute=$1 && shift  # so not a dry run to check the parameter parsing
+  [[ -n ${real_execute} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
+
   info "Finished ${FUNCNAME[0]} job"
+
+  echo "${remaining_args_string}"
 }
 
 flagstat() {
   info "Start ${FUNCNAME[0]} job"
 
+  local remaining_args_string=$1 && shift
+  local real_execute=$1 && shift  # so not a dry run to check the parameter parsing
+  [[ -n ${real_execute} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
+
+  local key
+  local input
+  local output
+  while [[ ${#remaining_args_string} -gt 0 ]]
+  do
+    key=$(get_first_word "${remaining_args_string}") || die "Could not get job arg"
+    case $key in
+      -i|--input)  # required
+        remaining_args_string=$(delete_first_word "${remaining_args_string}") || die "Could not remove key arg"
+        input=$(get_first_word "${remaining_args_string}") || die "Could not get ${key} arg"
+        remaining_args_string=$(delete_first_word "${remaining_args_string}") || die "Could not remove ${key} arg";;
+      -o|--output)  # required
+        remaining_args_string=$(delete_first_word "${remaining_args_string}") || die "Could not remove key arg"
+        output=$(get_first_word "${remaining_args_string}") || die "Could not get ${key} arg"
+        remaining_args_string=$(delete_first_word "${remaining_args_string}") || die "Could not remove ${key} arg";;
+      *)
+        break;;
+    esac
+  done
+
+  # sanity checks
+  local input_error=false
+  if [[ -z ${input} ]]; then
+    print_error_msg "Variable 'input' has not been set"
+    input_error=true
+  fi
+  if [[ -z ${output} ]]; then
+    print_error_msg "Variable 'output' has not been set"
+    input_error=true
+  fi
+  if [[ -n ${input} && ! "${input}" =~ ^gs://[*-/._a-zA-Z0-9]+.bam$ ]]; then
+    print_error_msg "Variable 'input' needs to be set to a path to a bam file in a bucket, e.g. gs://some-kind/of/path.bam"
+    input_error=true
+  fi
+  if [[ -n ${output} && ! "${output}" =~ ^gs://[-/._a-zA-Z0-9]+.flagstat ]]; then
+    print_error_msg "Variable 'output' needs to be set to a path of the form 'gs://some-kind/of/path.flagstat'"
+    input_error=true
+  fi
+  if [[ ${input_error} == true ]]; then
+    echo ""
+    print_flagstat_usage
+  fi
+
+  info "Passed ${FUNCNAME[0]} sanity checks"
+
+  if [[ "${real_execute}" != "${REAL_EXECUTE_TRUE}" ]]; then
+    info "Skip because of dry-run"
+  elif [[ $(file_exists_in_bucket "${output}") ]]; then
+    info "Skip because output file already exists in bucket"
+  else
+    do_flagstat "${input}" "${output}" || die "Could not run flagstat"
+  fi
+
   info "Finished ${FUNCNAME[0]} job"
+
+  echo "${remaining_args_string}"
+}
+
+do_flagstat() {
+  local input=$1 && shift
+  local output=$1 && shift
+  [[ -n ${output} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
+
+  local thread_count
+  local local_bam_path
+  local local_flagstat_path
+  thread_count=$(get_thread_count) || die "Could not get thread count"
+  local_bam_path=$(fill_local_cache "${input}") || die "Could not get local version of ${input}"
+  fill_local_cache "${input}.bai" || die "Could not get local version of ${input}.bai"
+  local_flagstat_path=$(get_local_cache_path "${output}") || die "Could not get local version of ${output}"
+
+  "${SAMBAMBA}" flagstat -t "${thread_count}" "${local_bam_path}" > "${local_flagstat_path}" || die "Could not run flagstat"
+
+  upload_from_local_cache "${output}"
+}
+
+fill_local_cache() {
+  local bucket_path=$1 && shift
+  [[ -n ${bucket_path} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
+  local local_path
+  local_path=$(get_local_cache_path "${bucket_path}") || die "Could not get local path for ${bucket_path}"
+
+  if [[ ! -f ${local_path} ]]; then
+    info "Download ${bucket_path}"
+    "${GSUTIL}" -m cp "${bucket_path}" "${local_path}"
+  fi
+  [[ -f ${local_path} ]] || die "Download of ${bucket_path} failed"
+  echo "${local_path}"
+}
+
+upload_from_local_cache() {
+  local bucket_path=$1 && shift
+  [[ -n ${bucket_path} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
+  local local_path
+  local_path=$(get_local_cache_path "${bucket_path}") || die "Could not get local path for ${bucket_path}"
+
+  "${GSUTIL}" -m cp "${local_path}" "${bucket_path}"
+  [[ $(file_exists_in_bucket "${bucket_path}") ]] || die "Upload to ${bucket_path} failed"
+}
+
+get_local_cache_path() {
+  local bucket_path=$1 && shift
+  [[ -n ${bucket_path} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
+  echo "${bucket_path/"gs://"/"${LOCAL_GCP_CACHE_DIR}/"}"
 }
 
 count_mapping_coords() {
   info "Start ${FUNCNAME[0]} job"
 
+  local remaining_args_string=$1 && shift
+  local real_execute=$1 && shift  # so not a dry run to check the parameter parsing
+  [[ -n ${real_execute} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
+
   info "Finished ${FUNCNAME[0]} job"
+
+  echo "${remaining_args_string}"
+}
+
+file_exists_in_bucket() {
+  local bucket_path=$1 && shift
+  [[ -n ${bucket_path} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
+  if [[ $(${GSUTIL} -q stat "${bucket_path}") ]]; then
+    return 0
+  else
+    return 1
+  fi
 }
 
 get_thread_count(){
@@ -117,7 +278,7 @@ get_thread_count(){
 trim_excess_whitespace() {
   local input=$1 && shift
   [[ -n ${input} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
-  echo "${*}" | xargs echo -n
+  echo "${input}" | xargs echo -n
 }
 
 get_first_word() {
